// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcbbsxxiqmrlidxudvfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjYmJzeHhpcW1ybGlkeHVkdmZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzU4NzksImV4cCI6MjA2OTkxMTg3OX0.mbo1IM4y2OLerE-6y-_9EMyplAE6NRd7IBEOBP_OYow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});